ARG DISTRIBUTION_TAG=latest
FROM debian:${DISTRIBUTION_TAG}

ENV DEBIAN_FRONTEND=noninteractive

# Enable apt source repository
RUN sed -i -e 's/^Types: deb/Types: deb deb-src/g' /etc/apt/sources.list.d/debian.sources

# Install packages
RUN apt-get update \
    && apt-get -y build-dep mozc \
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

# Copy code
WORKDIR /tmp/mozc-ut/
COPY ./scripts/ ./scripts/

ENTRYPOINT [ "/bin/bash" ]
